sonar.projectKey=andre-homelab_arthemis-brain_487f849f-4b5d-41e2-814f-65f4c8667e5d
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
