services:
  app:
    container_name: arthemis-watcher
    build:
      context: .
      dockerfile: Dockerfile
    image: arthemis-watcher-api
    ports:
      - "8082:8082"
    volumes:
      - ./.env:/app/.env
    networks:
      arthemis-edge:
        aliases:
          - watcher

networks:
  arthemis-edge:
    name: arthemis-edge
    external: true
